baseURL = "https://renatovargas.com"
languageCode = "es-ES"

theme = "renatovargas"

[languages.es]
    title = "Renato Vargas"
    languageName = "Spanish"
    weight = 1
[languages]
  [languages.en]
    title = "Renato Vargas"
    languageName = "English"
    weight = 2
